sudo: false
language: node_js
node_js: 6.6
env:
  global:
    - NODE_ENV=production
    - GH_REF=github.com/golmansax/blog.git
    - secure: "WmIVHkS0MnuCDqG3G6vc4fDl79tlIQtoZObr4ydspWkxJ68zmatXtBUX+mFd0zen88IW3jStxayJzXvaQwUy6C8EM2DHhAIev12zTZDhaM6lXNAF2F30ArpaezRT5MXS++TQi72Q+PENoEqm7fiR4UgxFphB1nYG02gGtW0iVzImTzsp0RURWHcxjEbDUBDjuhdakAB3GqFiegvxdNVaK3lUMLGGzX+L5QxycAudhcIe/Y1ZvHCNraNnhKp6ZxLApx92BbmGbkVive23mLFazP3DAU/1R3qCG5uyhdavDoMNFnGbxn85IjQWtgPEAQpbXZD5/2dYsvwC42TmsoIhaSPZvhk/9/M8ubq4phL7FvBbnQw8bnknPregk+9SFmykeKrYoK5B4jA/ywGvaKncJasObjOj9ldo/5+RSlvsJSlnJX5yd8VrfsjPVR7GGRD0XH5lPVsdi1rT/zfVTlnf04+YKZEnpsgQtDeJ7OteFzSkeSmXdtqTrxVu7uanoD78MS4pPgkRhWEArxeRP5wn4ZhLar1Kw525SZDilDYvO0eEC7Sqi1xS93FwUSetdrVwQflKreRnF6hubNgTXYDpKnw2CnIPi8lahZRZXeHPVF+YXI8CyUv2s0SvWpqijf8Cdxs/XdsU9ME0b08JjLkwTpoAIlPQnDoPTKFBZpNvXrM="

cache:
  directories:
    - node_modules # NPM packages
before_script:
  - roots compile -e production
after_success:
  - "./scripts/deploy_gh_pages.sh"
