sudo: false
language: node_js
node_js: 6.6

env:
  global:
    - NODE_ENV=production
    - GH_REF=github.com/golmansax/blog.git
    - secure: "jWOHaGBgoLSelJV/o+xy7lncj5svHazD7UWGgZWroFID15PQIQC+ZtUXqRJGD1LHrpooIx28HrZsL+1R1O9kOW4RqAR115sz3Q08Rg0SiCbCPLZNSaGkO2L01okqMrwDlyLfy77paItOw1518LN8lJsy951lfwTlUXGn5Eg2ql6VIPNL5KIK80Xp4oi4ZX9LQFct+b1ItQ0nTdXXM4JkDrvU3ytif6FjbOsO8jD9WCCIc6b/VYGQNRlS8p1g6E1PIm0gFgOgXAQCJVfiBDlgFHKBS86iGJuioq7/58YruuPCNdVSz2XRZ3GdoFywD+CB98bAaOtL3DpVrG7+jFlFeJjxZH6Vkp7+Bh6J3oybmW+DYhDhu9afriObrNkyU57qUhuC9116skLVmNBdHpz16IfoD801gN1f76RtI/CgMi/kziVgFg761LXtGmcaYli/ts9tUJDGFPwyPC9YmHI5doGjDWOs2asALFN/V10qZEDQycqNYKlLG/OwNl0ik3i1WjOT+KT89OP3wj2xQOzIntGfIvIgoQNY9HKohG/dKG38xzHHEfcT1FOjVO4ZNBdNPPQuYNcfQ3EOh/PEZqRPdq6g/XMRIDOcf+wnReTJULYNYzPKcVBjF2x0dWRm5VeuzL3pSbmFD448t9h9EOy7VtcwH3yiPheFF3CrahdfJUg="
    - secure: "AWfxQi2o/RRdTjbgcKXYD00tqlpIRDK8ww7AfJFx1U+2IhGL9NIzi9k0ZpUvCYDdLYD4YvmzstDHC5jeeKrO8ttAqeCkUYsNk1t2+kCyfr/fuJVRZFinrUPQi2atGUT4Zl6FU/MX0em7HC1ZkVwdcjVpA9213txo0/7mXZQeftPb6EUYbBlTx9sVBDSx0opHEDa2Rtrpime1Y4w8jRDaqN3AUn+RFSjBH7HGr+W/PirH6E0NWVD2nG86oZH+Hep7ZyNbBhDoahzLsuYSWJe0U9b4uUXH6xyP6B3AY9AN3FZxGHF/SBN2nLOLhFsHNcrubZF6vwN7EsXisTeDPLyeUREpNkFxTRIjdpri4tE2qazK/3ZfpoRsu4rPtIMh5keiixF8Y+QVKiNOwJccOsjOYNd0IhWFeJBba5gzlhhE9otQYEYDGamtOdnHzO9/ueHJfQv5QXnk71LfBZA9Q29rkUOF/DR4dXIvgtS6vvj8ZkXH6rxqtFFyDjyNZdi2Shr9UiBHYfjdf5FjJ79VBBAS0CSQ08KuFk/SBBgJLItXC92MsYyRi+t1CSNX9dAuhflzyzwmbYD1mMltB4BOSPEJVmBKQIK6rppUmPae4gRItdAJJNBvyUQF8JFOTG6evSSxnuSTgmyFI8KiphmCQ6EyAUNM1y67MAuW0Ga/bhsd2bU="
    - secure: "VGYmjSUfGTnCcLqyIUO51P+hlxg111wcorFK9ZuvMFnsw9xBK6p0zHVC8qhB+IhsMgPsMRAEfbMut8USKWhXucoWQb0TJZ0XOHNjKQekVIHTFztYglBpowMfQAfyjBDl1j4DGP77MadiWawiYj4tw8oC9+FXOrcVgKnhXsclKvLvJmcoj3R5r5qKudht9h7zz/wvqw6wn+Z6jdOXVwtfjLb+foJzG/D5dRn+PGpUPxjQMl86oLqSGqVfo1n3KusfoPIP9mD3yNpHXDVQp9vjkXQkeRdV3ISdo0N8ctQDTNbGxJu3V0Eo55Jnrjdhfohnhx+D4xhfqF2PgH4dXmUbfUKBmBHbUNBnj1W0DPlwc9Nmos+nz/7Ba1SB0AJIR6bWKAt68Oq0iELCbVbGf3mlmv/NzaTZW3tEohQA0fjlm/YNcgdQk/Voq4NIQGcCk6q2zhPx2z9yDjkf5Bqv6PlEyClgVaE8aC+y+8rfZD2BhA6uAbzUxL0FXu2CQ0yMH5OkvUKCGMbk9Uz8ARAWj0PkPEOEWIZDo3fvULnKVjPR80Kioc9ed72aYL6rXes7htjTnJUVpaJSIppK2UfFnHQyp+CZVMSK4aWs4XaM1U3PilcKRI+VLhDgTC4GXexrSqnXAeqjJf5Iioirvu01nyqaBJHl980rvSb2VHIxJu/68yI="

cache:
  directories:
    - node_modules # NPM packages

before_script:
  - npm run build
script:
  - npm run lint-js
  - npm run lint-pug

after_success:
  - "./scripts/deploy_gh_pages.sh"
