sudo: false
language: node_js
node_js: 6.6
env:
  global:
    - NODE_ENV=production
    - GH_REF=github.com/golmansax/blog.git
    - secure: "jWOHaGBgoLSelJV/o+xy7lncj5svHazD7UWGgZWroFID15PQIQC+ZtUXqRJGD1LHrpooIx28HrZsL+1R1O9kOW4RqAR115sz3Q08Rg0SiCbCPLZNSaGkO2L01okqMrwDlyLfy77paItOw1518LN8lJsy951lfwTlUXGn5Eg2ql6VIPNL5KIK80Xp4oi4ZX9LQFct+b1ItQ0nTdXXM4JkDrvU3ytif6FjbOsO8jD9WCCIc6b/VYGQNRlS8p1g6E1PIm0gFgOgXAQCJVfiBDlgFHKBS86iGJuioq7/58YruuPCNdVSz2XRZ3GdoFywD+CB98bAaOtL3DpVrG7+jFlFeJjxZH6Vkp7+Bh6J3oybmW+DYhDhu9afriObrNkyU57qUhuC9116skLVmNBdHpz16IfoD801gN1f76RtI/CgMi/kziVgFg761LXtGmcaYli/ts9tUJDGFPwyPC9YmHI5doGjDWOs2asALFN/V10qZEDQycqNYKlLG/OwNl0ik3i1WjOT+KT89OP3wj2xQOzIntGfIvIgoQNY9HKohG/dKG38xzHHEfcT1FOjVO4ZNBdNPPQuYNcfQ3EOh/PEZqRPdq6g/XMRIDOcf+wnReTJULYNYzPKcVBjF2x0dWRm5VeuzL3pSbmFD448t9h9EOy7VtcwH3yiPheFF3CrahdfJUg="

cache:
  directories:
    - node_modules # NPM packages
before_script:
  - roots compile -e production
after_success:
  - "./scripts/deploy_gh_pages.sh"
