sudo: false
language: node_js
node_js: 6.6
env:
  global:
    - NODE_ENV=production
    - GH_REF=github.com/golmansax/blog.git
    - secure: "BpYlyVIpSj4s8bMOpHyYp5s83nMXIMUXMf8lSkxc24I693CCLK9q529in8VEvCX2GIp0Ex3onf1+OdWHjh6ZwVNIgJ//OhNUwYNiqoApaH5l6ncy0xDXN5+igEah7PZB2p+ODHLxZZCnhsImo88I7tP1Ru6Zc5mh/u2rrsA+Kdt7Qnlbj0YbR8pgItCbrXkCaqsPOgnYr9L8I1VrG9F24E/ZFSAGz211A9vEm+etuCSIkQlUMqfzl+VtnuYY4t9N6uHZuZJJbah/8F+uZqRpkm7z7QphpdZFXiFjzYp2x9FfPQqIpeNi2SgjIpf3BoCqfBkZXq2LRiLaxNJALau45ztUqH8fJyvW/isIu81D5rG3sfSlPzuhq0kK5xvkj++x49rIIX6G33BWPCZkl51YHUy1hdKuKDINsY/ZIXjwOvDoaaq0Mw3S/6PZ/lDDZJVucRMdZQ5d41kEAbcr1GwVkWY/WHjGZTQF2xlMqJeToMzEdMW8MM1FwXtbXgCMVtwIq4Jqqd4y9V4yU+H895K40uJyufuiEw0VaDLjI0yU+4NZR5JjvFLtBIrvEdKsrKQ3cYicZepS6A39pl8wMasmkMd1HpHySkxuotdHLWSsthyArAO0rMG1XX9aXAFXfvRwDu4PyRUaUAQtW5SuAi/WOIuntqdXPdFZPVbWZNLClps="
cache:
  directories:
    - node_modules # NPM packages
before_script:
  - roots compile -e production
after_success:
  - "./scripts/deploy_gh_pages.sh"
