name: Node.js CI

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      AMAZON_AFFILIATE_ID: ${{ secrets.AMAZON_AFFILIATE_ID }}
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_DELIVERY_API_KEY: ${{ secrets.CONTENTFUL_DELIVERY_API_KEY }}
      CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN }}
      NGROK_ACCESS_TOKEN: ${{ secrets.NGROK_ACCESS_TOKEN }}
      HEAP_ANALYTICS_APP_ID: ${{ secrets.HEAP_ANALYTICS_APP_ID }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/node_modules
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-yarn-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - run: yarn install --production=false
      - run: yarn build:assets
      - run: yarn build:views
      - run: yarn build:redirect_pages

      - run: yarn lint:js
      - run: yarn lint:pug
      - run: yarn lint:scss

      - name: Deploy with gh-pages
        if: github.ref == 'refs/heads/master'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
